// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WeddingPlanner2.Models;

namespace WeddingPlanner2.Migrations
{
    [DbContext(typeof(MyContext))]
    [Migration("20190711194755_OneMigration")]
    partial class OneMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("WeddingPlanner2.Models.Guest", b =>
                {
                    b.Property<int>("GuestID")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("UserID");

                    b.Property<int>("WeddingID");

                    b.HasKey("GuestID");

                    b.HasIndex("UserID");

                    b.HasIndex("WeddingID");

                    b.ToTable("guests");
                });

            modelBuilder.Entity("WeddingPlanner2.Models.User", b =>
                {
                    b.Property<int>("UserID")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("CreatedAt");

                    b.Property<string>("Email")
                        .IsRequired();

                    b.Property<string>("FirstName")
                        .IsRequired();

                    b.Property<string>("LastName")
                        .IsRequired();

                    b.Property<string>("Password")
                        .IsRequired();

                    b.Property<DateTime>("UpdatedAt");

                    b.HasKey("UserID");

                    b.ToTable("users");
                });

            modelBuilder.Entity("WeddingPlanner2.Models.Wedding", b =>
                {
                    b.Property<int>("WeddingID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Address");

                    b.Property<string>("Bride");

                    b.Property<DateTime>("CreatedAt");

                    b.Property<DateTime>("Date");

                    b.Property<string>("Groom");

                    b.Property<int>("OrganizerID");

                    b.Property<DateTime>("UpdatedAt");

                    b.HasKey("WeddingID");

                    b.HasIndex("OrganizerID");

                    b.ToTable("weddings");
                });

            modelBuilder.Entity("WeddingPlanner2.Models.Guest", b =>
                {
                    b.HasOne("WeddingPlanner2.Models.User", "User")
                        .WithMany("Weddings")
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("WeddingPlanner2.Models.Wedding", "Wedding")
                        .WithMany("Guests")
                        .HasForeignKey("WeddingID")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("WeddingPlanner2.Models.Wedding", b =>
                {
                    b.HasOne("WeddingPlanner2.Models.User", "Organizer")
                        .WithMany()
                        .HasForeignKey("OrganizerID")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
